# Generated by Django 2.1.1 on 2018-09-08 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Awards',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Title', models.CharField(max_length=30)),
                ('img', models.ImageField(upload_to='media')),
            ],
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=30)),
                ('Title_img', models.ImageField(upload_to='media')),
                ('Full_img', models.ImageField(upload_to='media')),
                ('Description', models.CharField(max_length=30)),
                ('Venue', models.CharField(max_length=30)),
                ('duration', models.CharField(max_length=30)),
                ('Date', models.DateField()),
                ('Conducted_by', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Home',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.ImageField(upload_to='media')),
            ],
        ),
        migrations.CreateModel(
            name='Members',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=30)),
                ('img', models.ImageField(upload_to='media')),
            ],
        ),
        migrations.CreateModel(
            name='Workshop',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=30)),
                ('title_img', models.ImageField(upload_to='media')),
                ('descrip', models.CharField(max_length=30)),
                ('full_img', models.ImageField(upload_to='media')),
                ('venue', models.CharField(max_length=30)),
                ('time', models.DateField()),
                ('conducted_by', models.CharField(max_length=30)),
                ('duration', models.CharField(max_length=30)),
            ],
        ),
    ]
